- warn: {lhs: x >> return y,  rhs: x $> y}
- warn: {lhs: return x << y,  rhs: x <$ y}
- warn: {lhs: return x,       rhs: pure x}

# Replace a $ b $ c with a . b $ c
- group: {name: dollar, enabled: true}

# Hasmin specific
- warn: {lhs: skipComments *> x <* skipComments, rhs: lexeme x}

